/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GiftBoxesRouteImport } from './routes/gift-boxes'
import { Route as GiftBoxRouteImport } from './routes/gift-box'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AiFinderRouteImport } from './routes/ai-finder'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as CCategorySlugRouteImport } from './routes/c.$categorySlug'
import { Route as BoxSlugRouteImport } from './routes/box.$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api.razorpay-webhook'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReadyBoxesRouteImport } from './routes/admin.ready-boxes'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminEmptyBoxesRouteImport } from './routes/admin.empty-boxes'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAiLogsRouteImport } from './routes/admin.ai-logs'
import { Route as AccountReferralsRouteImport } from './routes/account_.referrals'
import { Route as ApiCronBirthdayRemindersRouteImport } from './routes/api.cron.birthday-reminders'
import { Route as AccountOrdersOrderIdInvoiceRouteImport } from './routes/account_.orders.$orderId.invoice'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftBoxesRoute = GiftBoxesRouteImport.update({
  id: '/gift-boxes',
  path: '/gift-boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftBoxRoute = GiftBoxRouteImport.update({
  id: '/gift-box',
  path: '/gift-box',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFinderRoute = AiFinderRouteImport.update({
  id: '/ai-finder',
  path: '/ai-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategorySlugRoute = CCategorySlugRouteImport.update({
  id: '/c/$categorySlug',
  path: '/c/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxSlugRoute = BoxSlugRouteImport.update({
  id: '/box/$slug',
  path: '/box/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay-webhook',
  path: '/api/razorpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadyBoxesRoute = AdminReadyBoxesRouteImport.update({
  id: '/ready-boxes',
  path: '/ready-boxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmptyBoxesRoute = AdminEmptyBoxesRouteImport.update({
  id: '/empty-boxes',
  path: '/empty-boxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiLogsRoute = AdminAiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AccountReferralsRoute = AccountReferralsRouteImport.update({
  id: '/account_/referrals',
  path: '/account/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBirthdayRemindersRoute =
  ApiCronBirthdayRemindersRouteImport.update({
    id: '/api/cron/birthday-reminders',
    path: '/api/cron/birthday-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountOrdersOrderIdInvoiceRoute =
  AccountOrdersOrderIdInvoiceRouteImport.update({
    id: '/account_/orders/$orderId/invoice',
    path: '/account/orders/$orderId/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-finder': typeof AiFinderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gift-box': typeof GiftBoxRoute
  '/gift-boxes': typeof GiftBoxesRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/account/referrals': typeof AccountReferralsRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/empty-boxes': typeof AdminEmptyBoxesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/ready-boxes': typeof AdminReadyBoxesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/box/$slug': typeof BoxSlugRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/api/cron/birthday-reminders': typeof ApiCronBirthdayRemindersRoute
  '/account/orders/$orderId/invoice': typeof AccountOrdersOrderIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-finder': typeof AiFinderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gift-box': typeof GiftBoxRoute
  '/gift-boxes': typeof GiftBoxesRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/account/referrals': typeof AccountReferralsRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/empty-boxes': typeof AdminEmptyBoxesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/ready-boxes': typeof AdminReadyBoxesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/box/$slug': typeof BoxSlugRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/api/cron/birthday-reminders': typeof ApiCronBirthdayRemindersRoute
  '/account/orders/$orderId/invoice': typeof AccountOrdersOrderIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-finder': typeof AiFinderRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gift-box': typeof GiftBoxRoute
  '/gift-boxes': typeof GiftBoxesRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/account_/referrals': typeof AccountReferralsRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/empty-boxes': typeof AdminEmptyBoxesRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/ready-boxes': typeof AdminReadyBoxesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/box/$slug': typeof BoxSlugRoute
  '/c/$categorySlug': typeof CCategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/p/$slug': typeof PSlugRoute
  '/api/cron/birthday-reminders': typeof ApiCronBirthdayRemindersRoute
  '/account_/orders/$orderId/invoice': typeof AccountOrdersOrderIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-finder'
    | '/cart'
    | '/checkout'
    | '/gift-box'
    | '/gift-boxes'
    | '/help'
    | '/notifications'
    | '/search'
    | '/wishlist'
    | '/account/referrals'
    | '/admin/ai-logs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/empty-boxes'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/ready-boxes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/razorpay-webhook'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/box/$slug'
    | '/c/$categorySlug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$slug'
    | '/api/cron/birthday-reminders'
    | '/account/orders/$orderId/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-finder'
    | '/cart'
    | '/checkout'
    | '/gift-box'
    | '/gift-boxes'
    | '/help'
    | '/notifications'
    | '/search'
    | '/wishlist'
    | '/account/referrals'
    | '/admin/ai-logs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/empty-boxes'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/ready-boxes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/razorpay-webhook'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/box/$slug'
    | '/c/$categorySlug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$slug'
    | '/api/cron/birthday-reminders'
    | '/account/orders/$orderId/invoice'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/ai-finder'
    | '/cart'
    | '/checkout'
    | '/gift-box'
    | '/gift-boxes'
    | '/help'
    | '/notifications'
    | '/search'
    | '/wishlist'
    | '/account_/referrals'
    | '/admin/ai-logs'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/empty-boxes'
    | '/admin/homepage'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/ready-boxes'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/razorpay-webhook'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/box/$slug'
    | '/c/$categorySlug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/p/$slug'
    | '/api/cron/birthday-reminders'
    | '/account_/orders/$orderId/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiFinderRoute: typeof AiFinderRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  GiftBoxRoute: typeof GiftBoxRoute
  GiftBoxesRoute: typeof GiftBoxesRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  AccountReferralsRoute: typeof AccountReferralsRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BoxSlugRoute: typeof BoxSlugRoute
  CCategorySlugRoute: typeof CCategorySlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PSlugRoute: typeof PSlugRoute
  ApiCronBirthdayRemindersRoute: typeof ApiCronBirthdayRemindersRoute
  AccountOrdersOrderIdInvoiceRoute: typeof AccountOrdersOrderIdInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-boxes': {
      id: '/gift-boxes'
      path: '/gift-boxes'
      fullPath: '/gift-boxes'
      preLoaderRoute: typeof GiftBoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-box': {
      id: '/gift-box'
      path: '/gift-box'
      fullPath: '/gift-box'
      preLoaderRoute: typeof GiftBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-finder': {
      id: '/ai-finder'
      path: '/ai-finder'
      fullPath: '/ai-finder'
      preLoaderRoute: typeof AiFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$categorySlug': {
      id: '/c/$categorySlug'
      path: '/c/$categorySlug'
      fullPath: '/c/$categorySlug'
      preLoaderRoute: typeof CCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/$slug': {
      id: '/box/$slug'
      path: '/box/$slug'
      fullPath: '/box/$slug'
      preLoaderRoute: typeof BoxSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay-webhook': {
      id: '/api/razorpay-webhook'
      path: '/api/razorpay-webhook'
      fullPath: '/api/razorpay-webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ready-boxes': {
      id: '/admin/ready-boxes'
      path: '/ready-boxes'
      fullPath: '/admin/ready-boxes'
      preLoaderRoute: typeof AdminReadyBoxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empty-boxes': {
      id: '/admin/empty-boxes'
      path: '/empty-boxes'
      fullPath: '/admin/empty-boxes'
      preLoaderRoute: typeof AdminEmptyBoxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-logs': {
      id: '/admin/ai-logs'
      path: '/ai-logs'
      fullPath: '/admin/ai-logs'
      preLoaderRoute: typeof AdminAiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account_/referrals': {
      id: '/account_/referrals'
      path: '/account/referrals'
      fullPath: '/account/referrals'
      preLoaderRoute: typeof AccountReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/birthday-reminders': {
      id: '/api/cron/birthday-reminders'
      path: '/api/cron/birthday-reminders'
      fullPath: '/api/cron/birthday-reminders'
      preLoaderRoute: typeof ApiCronBirthdayRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/orders/$orderId/invoice': {
      id: '/account_/orders/$orderId/invoice'
      path: '/account/orders/$orderId/invoice'
      fullPath: '/account/orders/$orderId/invoice'
      preLoaderRoute: typeof AccountOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiLogsRoute: typeof AdminAiLogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminEmptyBoxesRoute: typeof AdminEmptyBoxesRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReadyBoxesRoute: typeof AdminReadyBoxesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiLogsRoute: AdminAiLogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminEmptyBoxesRoute: AdminEmptyBoxesRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReadyBoxesRoute: AdminReadyBoxesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AiFinderRoute: AiFinderRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  GiftBoxRoute: GiftBoxRoute,
  GiftBoxesRoute: GiftBoxesRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  AccountReferralsRoute: AccountReferralsRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BoxSlugRoute: BoxSlugRoute,
  CCategorySlugRoute: CCategorySlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PSlugRoute: PSlugRoute,
  ApiCronBirthdayRemindersRoute: ApiCronBirthdayRemindersRoute,
  AccountOrdersOrderIdInvoiceRoute: AccountOrdersOrderIdInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
